package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addmaterialtypes generated by hbm2java
 */
@Entity
@Table(name="addmaterialtypes"
    ,catalog="openeduuz"
)
public class Addmaterialtypes  implements java.io.Serializable {


     private int addMaterialTypeId;
     private String addMaterialTypeName;
     private String addMaterialDescription;
     private Set addmaterialandtypesmappings = new HashSet(0);

    public Addmaterialtypes() {
    }

	
    public Addmaterialtypes(int addMaterialTypeId) {
        this.addMaterialTypeId = addMaterialTypeId;
    }
    public Addmaterialtypes(int addMaterialTypeId, String addMaterialTypeName, String addMaterialDescription, Set addmaterialandtypesmappings) {
       this.addMaterialTypeId = addMaterialTypeId;
       this.addMaterialTypeName = addMaterialTypeName;
       this.addMaterialDescription = addMaterialDescription;
       this.addmaterialandtypesmappings = addmaterialandtypesmappings;
    }
   
     @Id 

    
    @Column(name="addMaterialTypeID", unique=true, nullable=false)
    public int getAddMaterialTypeId() {
        return this.addMaterialTypeId;
    }
    
    public void setAddMaterialTypeId(int addMaterialTypeId) {
        this.addMaterialTypeId = addMaterialTypeId;
    }

    
    @Column(name="addMaterialTypeName", length=45)
    public String getAddMaterialTypeName() {
        return this.addMaterialTypeName;
    }
    
    public void setAddMaterialTypeName(String addMaterialTypeName) {
        this.addMaterialTypeName = addMaterialTypeName;
    }

    
    @Column(name="addMaterialDescription")
    public String getAddMaterialDescription() {
        return this.addMaterialDescription;
    }
    
    public void setAddMaterialDescription(String addMaterialDescription) {
        this.addMaterialDescription = addMaterialDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="addmaterialtypes")
    public Set getAddmaterialandtypesmappings() {
        return this.addmaterialandtypesmappings;
    }
    
    public void setAddmaterialandtypesmappings(Set addmaterialandtypesmappings) {
        this.addmaterialandtypesmappings = addmaterialandtypesmappings;
    }




}


