package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddmaterialandtypesmappingId generated by hbm2java
 */
@Embeddable
public class AddmaterialandtypesmappingId  implements java.io.Serializable {


     private int mappingId;
     private int lectonAddMaterialsAddMaterialId;

    public AddmaterialandtypesmappingId() {
    }

    public AddmaterialandtypesmappingId(int mappingId, int lectonAddMaterialsAddMaterialId) {
       this.mappingId = mappingId;
       this.lectonAddMaterialsAddMaterialId = lectonAddMaterialsAddMaterialId;
    }
   


    @Column(name="mappingID", nullable=false)
    public int getMappingId() {
        return this.mappingId;
    }
    
    public void setMappingId(int mappingId) {
        this.mappingId = mappingId;
    }


    @Column(name="lectonAddMaterials_addMaterialID", nullable=false)
    public int getLectonAddMaterialsAddMaterialId() {
        return this.lectonAddMaterialsAddMaterialId;
    }
    
    public void setLectonAddMaterialsAddMaterialId(int lectonAddMaterialsAddMaterialId) {
        this.lectonAddMaterialsAddMaterialId = lectonAddMaterialsAddMaterialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AddmaterialandtypesmappingId) ) return false;
		 AddmaterialandtypesmappingId castOther = ( AddmaterialandtypesmappingId ) other; 
         
		 return (this.getMappingId()==castOther.getMappingId())
 && (this.getLectonAddMaterialsAddMaterialId()==castOther.getLectonAddMaterialsAddMaterialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMappingId();
         result = 37 * result + this.getLectonAddMaterialsAddMaterialId();
         return result;
   }   


}


