package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answersforquestions generated by hbm2java
 */
@Entity
@Table(name="answersforquestions"
    ,catalog="openeduuz"
)
public class Answersforquestions  implements java.io.Serializable {


     private Integer answerId;
     private Lectionquestions lectionquestions;
     private String answerRu;
     private String answerUz;
     private String answerEn;
     private Boolean isTrue;

    public Answersforquestions() {
    }

    public Answersforquestions(Lectionquestions lectionquestions, String answerRu, String answerUz, String answerEn, Boolean isTrue) {
       this.lectionquestions = lectionquestions;
       this.answerRu = answerRu;
       this.answerUz = answerUz;
       this.answerEn = answerEn;
       this.isTrue = isTrue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="answerID", unique=true, nullable=false)
    public Integer getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questionID")
    public Lectionquestions getLectionquestions() {
        return this.lectionquestions;
    }
    
    public void setLectionquestions(Lectionquestions lectionquestions) {
        this.lectionquestions = lectionquestions;
    }

    
    @Column(name="answerRU")
    public String getAnswerRu() {
        return this.answerRu;
    }
    
    public void setAnswerRu(String answerRu) {
        this.answerRu = answerRu;
    }

    
    @Column(name="answerUZ")
    public String getAnswerUz() {
        return this.answerUz;
    }
    
    public void setAnswerUz(String answerUz) {
        this.answerUz = answerUz;
    }

    
    @Column(name="answerEN")
    public String getAnswerEn() {
        return this.answerEn;
    }
    
    public void setAnswerEn(String answerEn) {
        this.answerEn = answerEn;
    }

    
    @Column(name="isTrue")
    public Boolean getIsTrue() {
        return this.isTrue;
    }
    
    public void setIsTrue(Boolean isTrue) {
        this.isTrue = isTrue;
    }




}


