package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name="courses"
    ,catalog="openeduuz"
)
public class Courses  implements java.io.Serializable {


     private Integer courseId;
     private String courseNameRu;
     private String courseNameUz;
     private String courseNameEn;
     private Integer courseLections;
     private String courseDescriptionRu;
     private String courseDescriptionUz;
     private String courseDescriptionEn;
     private Boolean isActive;
     private Set courselectionses = new HashSet(0);
     private byte[] courseImage;
     private String courseAuthor;

    public byte[] getCourseImage() {
        return courseImage;
    }

    public void setCourseImage(byte[] courseImage) {
        this.courseImage = courseImage;
    }

    public String getCourseAuthor() {
        return courseAuthor;
    }

    public void setCourseAuthor(String courseAuthor) {
        this.courseAuthor = courseAuthor;
    }
     
     
    public Courses() {
    }

	
    public Courses(String courseNameRu) {
        this.courseNameRu = courseNameRu;
    }
    public Courses(String courseNameRu, String courseNameUz, String courseNameEn, Integer courseLections, String courseDescriptionRu, String courseDescriptionUz, String courseDescriptionEn, Boolean isActive, Set courselectionses) {
       this.courseNameRu = courseNameRu;
       this.courseNameUz = courseNameUz;
       this.courseNameEn = courseNameEn;
       this.courseLections = courseLections;
       this.courseDescriptionRu = courseDescriptionRu;
       this.courseDescriptionUz = courseDescriptionUz;
       this.courseDescriptionEn = courseDescriptionEn;
       this.isActive = isActive;
       this.courselectionses = courselectionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="courseId", unique=true, nullable=false)
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    
    @Column(name="courseNameRU", nullable=false)
    public String getCourseNameRu() {
        return this.courseNameRu;
    }
    
    public void setCourseNameRu(String courseNameRu) {
        this.courseNameRu = courseNameRu;
    }

    
    @Column(name="courseNameUZ")
    public String getCourseNameUz() {
        return this.courseNameUz;
    }
    
    public void setCourseNameUz(String courseNameUz) {
        this.courseNameUz = courseNameUz;
    }

    
    @Column(name="courseNameEN")
    public String getCourseNameEn() {
        return this.courseNameEn;
    }
    
    public void setCourseNameEn(String courseNameEn) {
        this.courseNameEn = courseNameEn;
    }

    
    @Column(name="courseLections")
    public Integer getCourseLections() {
        return this.courseLections;
    }
    
    public void setCourseLections(Integer courseLections) {
        this.courseLections = courseLections;
    }

    
    @Column(name="courseDescriptionRU", length=65535)
    public String getCourseDescriptionRu() {
        return this.courseDescriptionRu;
    }
    
    public void setCourseDescriptionRu(String courseDescriptionRu) {
        this.courseDescriptionRu = courseDescriptionRu;
    }

    
    @Column(name="courseDescriptionUZ", length=65535)
    public String getCourseDescriptionUz() {
        return this.courseDescriptionUz;
    }
    
    public void setCourseDescriptionUz(String courseDescriptionUz) {
        this.courseDescriptionUz = courseDescriptionUz;
    }

    
    @Column(name="courseDescriptionEN", length=65535)
    public String getCourseDescriptionEn() {
        return this.courseDescriptionEn;
    }
    
    public void setCourseDescriptionEn(String courseDescriptionEn) {
        this.courseDescriptionEn = courseDescriptionEn;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courses")
    public Set getCourselectionses() {
        return this.courselectionses;
    }
    
    public void setCourselectionses(Set courselectionses) {
        this.courselectionses = courselectionses;
    }




}


