package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lectonaddmaterials generated by hbm2java
 */
@Entity
@Table(name="lectonaddmaterials"
    ,catalog="openeduuz"
)
public class Lectonaddmaterials  implements java.io.Serializable {


     private Integer addMaterialId;
     private Courselections courselections;
     private String addMaterialDescription;
     private byte[] addMaterialRu;
     private byte[] addMaterialUz;
     private byte[] addMaterialEn;
     private Set addmaterialandtypesmappings = new HashSet(0);

    public Lectonaddmaterials() {
    }

    public Lectonaddmaterials(Courselections courselections, String addMaterialDescription, byte[] addMaterialRu, byte[] addMaterialUz, byte[] addMaterialEn, Set addmaterialandtypesmappings) {
       this.courselections = courselections;
       this.addMaterialDescription = addMaterialDescription;
       this.addMaterialRu = addMaterialRu;
       this.addMaterialUz = addMaterialUz;
       this.addMaterialEn = addMaterialEn;
       this.addmaterialandtypesmappings = addmaterialandtypesmappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="addMaterialID", unique=true, nullable=false)
    public Integer getAddMaterialId() {
        return this.addMaterialId;
    }
    
    public void setAddMaterialId(Integer addMaterialId) {
        this.addMaterialId = addMaterialId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lectionID")
    public Courselections getCourselections() {
        return this.courselections;
    }
    
    public void setCourselections(Courselections courselections) {
        this.courselections = courselections;
    }

    
    @Column(name="addMaterialDescription")
    public String getAddMaterialDescription() {
        return this.addMaterialDescription;
    }
    
    public void setAddMaterialDescription(String addMaterialDescription) {
        this.addMaterialDescription = addMaterialDescription;
    }

    
    @Column(name="addMaterialRU")
    public byte[] getAddMaterialRu() {
        return this.addMaterialRu;
    }
    
    public void setAddMaterialRu(byte[] addMaterialRu) {
        this.addMaterialRu = addMaterialRu;
    }

    
    @Column(name="addMaterialUZ")
    public byte[] getAddMaterialUz() {
        return this.addMaterialUz;
    }
    
    public void setAddMaterialUz(byte[] addMaterialUz) {
        this.addMaterialUz = addMaterialUz;
    }

    
    @Column(name="addMaterialEN")
    public byte[] getAddMaterialEn() {
        return this.addMaterialEn;
    }
    
    public void setAddMaterialEn(byte[] addMaterialEn) {
        this.addMaterialEn = addMaterialEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lectonaddmaterials")
    public Set getAddmaterialandtypesmappings() {
        return this.addmaterialandtypesmappings;
    }
    
    public void setAddmaterialandtypesmappings(Set addmaterialandtypesmappings) {
        this.addmaterialandtypesmappings = addmaterialandtypesmappings;
    }




}


