package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lectionmainmaterials generated by hbm2java
 */
@Entity
@Table(name="lectionmainmaterials"
    ,catalog="openeduuz"
)
public class Lectionmainmaterials  implements java.io.Serializable {


     private Integer materialId;
     private Courselections courselections;
     private byte[] lectionPdfru;
     private byte[] lectionPdfuz;
     private byte[] lectionPdfen;
     private byte[] homeTaskRu;
     private byte[] homeTaskUz;
     private byte[] homeTaskEn;

    public Lectionmainmaterials() {
    }

	
    public Lectionmainmaterials(byte[] lectionPdfru) {
        this.lectionPdfru = lectionPdfru;
    }
    public Lectionmainmaterials(Courselections courselections, byte[] lectionPdfru, byte[] lectionPdfuz, byte[] lectionPdfen, byte[] homeTaskRu, byte[] homeTaskUz, byte[] homeTaskEn) {
       this.courselections = courselections;
       this.lectionPdfru = lectionPdfru;
       this.lectionPdfuz = lectionPdfuz;
       this.lectionPdfen = lectionPdfen;
       this.homeTaskRu = homeTaskRu;
       this.homeTaskUz = homeTaskUz;
       this.homeTaskEn = homeTaskEn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="materialID", unique=true, nullable=false)
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lectionID")
    public Courselections getCourselections() {
        return this.courselections;
    }
    
    public void setCourselections(Courselections courselections) {
        this.courselections = courselections;
    }

    
    @Column(name="lectionPDFru", nullable=false)
    public byte[] getLectionPdfru() {
        return this.lectionPdfru;
    }
    
    public void setLectionPdfru(byte[] lectionPdfru) {
        this.lectionPdfru = lectionPdfru;
    }

    
    @Column(name="lectionPDFuz")
    public byte[] getLectionPdfuz() {
        return this.lectionPdfuz;
    }
    
    public void setLectionPdfuz(byte[] lectionPdfuz) {
        this.lectionPdfuz = lectionPdfuz;
    }

    
    @Column(name="lectionPDFen")
    public byte[] getLectionPdfen() {
        return this.lectionPdfen;
    }
    
    public void setLectionPdfen(byte[] lectionPdfen) {
        this.lectionPdfen = lectionPdfen;
    }

    
    @Column(name="homeTaskRU")
    public byte[] getHomeTaskRu() {
        return this.homeTaskRu;
    }
    
    public void setHomeTaskRu(byte[] homeTaskRu) {
        this.homeTaskRu = homeTaskRu;
    }

    
    @Column(name="homeTaskUZ")
    public byte[] getHomeTaskUz() {
        return this.homeTaskUz;
    }
    
    public void setHomeTaskUz(byte[] homeTaskUz) {
        this.homeTaskUz = homeTaskUz;
    }

    
    @Column(name="homeTaskEN")
    public byte[] getHomeTaskEn() {
        return this.homeTaskEn;
    }
    
    public void setHomeTaskEn(byte[] homeTaskEn) {
        this.homeTaskEn = homeTaskEn;
    }




}


