package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionandtypesmappingId generated by hbm2java
 */
@Embeddable
public class QuestionandtypesmappingId  implements java.io.Serializable {


     private int mappingId;
     private int lectionQuestionsQuestionId;

    public QuestionandtypesmappingId() {
    }

    public QuestionandtypesmappingId(int mappingId, int lectionQuestionsQuestionId) {
       this.mappingId = mappingId;
       this.lectionQuestionsQuestionId = lectionQuestionsQuestionId;
    }
   


    @Column(name="mappingID", nullable=false)
    public int getMappingId() {
        return this.mappingId;
    }
    
    public void setMappingId(int mappingId) {
        this.mappingId = mappingId;
    }


    @Column(name="lectionQuestions_questionID", nullable=false)
    public int getLectionQuestionsQuestionId() {
        return this.lectionQuestionsQuestionId;
    }
    
    public void setLectionQuestionsQuestionId(int lectionQuestionsQuestionId) {
        this.lectionQuestionsQuestionId = lectionQuestionsQuestionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionandtypesmappingId) ) return false;
		 QuestionandtypesmappingId castOther = ( QuestionandtypesmappingId ) other; 
         
		 return (this.getMappingId()==castOther.getMappingId())
 && (this.getLectionQuestionsQuestionId()==castOther.getLectionQuestionsQuestionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMappingId();
         result = 37 * result + this.getLectionQuestionsQuestionId();
         return result;
   }   


}


