package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersandrolesmappingId generated by hbm2java
 */
@Embeddable
public class UsersandrolesmappingId  implements java.io.Serializable {


     private int mappingId;
     private String userEmail;

    public UsersandrolesmappingId() {
    }

    public UsersandrolesmappingId(int mappingId, String userEmail) {
       this.mappingId = mappingId;
       this.userEmail = userEmail;
    }
   


    @Column(name="mappingID", nullable=false)
    public int getMappingId() {
        return this.mappingId;
    }
    
    public void setMappingId(int mappingId) {
        this.mappingId = mappingId;
    }


    @Column(name="user_email", nullable=false, length=45)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersandrolesmappingId) ) return false;
		 UsersandrolesmappingId castOther = ( UsersandrolesmappingId ) other; 
         
		 return (this.getMappingId()==castOther.getMappingId())
 && ( (this.getUserEmail()==castOther.getUserEmail()) || ( this.getUserEmail()!=null && castOther.getUserEmail()!=null && this.getUserEmail().equals(castOther.getUserEmail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMappingId();
         result = 37 * result + ( getUserEmail() == null ? 0 : this.getUserEmail().hashCode() );
         return result;
   }   


}


