package entity;
// Generated 02.04.2016 23:34:41 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usersandrolesmapping generated by hbm2java
 */
@Entity
@Table(name="usersandrolesmapping"
    ,catalog="openeduuz"
)
public class Usersandrolesmapping  implements java.io.Serializable {


     private UsersandrolesmappingId id;
     private Roles roles;
     private User user;

    public Usersandrolesmapping() {
    }

    public Usersandrolesmapping(UsersandrolesmappingId id, Roles roles, User user) {
       this.id = id;
       this.roles = roles;
       this.user = user;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mappingId", column=@Column(name="mappingID", nullable=false) ), 
        @AttributeOverride(name="userEmail", column=@Column(name="user_email", nullable=false, length=45) ) } )
    public UsersandrolesmappingId getId() {
        return this.id;
    }
    
    public void setId(UsersandrolesmappingId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roleID", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_email", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


